# Generated by Django 4.2.1 on 2023-06-01 23:56

import apps.api.helpers.custom_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to=apps.api.helpers.custom_upload.csv_upload_path)),
            ],
        ),
    ]
