# Generated by Django 4.2.1 on 2023-06-01 15:49

import apps.api.helpers.custom_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_uploadfile_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='csv_file',
            field=models.FileField(upload_to=apps.api.helpers.custom_upload.csv_upload_path),
        ),
    ]
